# Generated by Django 3.0.3 on 2020-09-11 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0002_contactmessage_projectidea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectidea',
            name='project_documents',
        ),
    ]
